dist: bionic
language: java

script:
  - mkdir -p build || travis_terminate 1
  - curl -s 'http://d.defold.com/stable/info.json' | python3 -c "import sys, json; print('https://d.defold.com/archive/' + json.load(sys.stdin)['sha1'] + '/bob/bob.jar')" | wget --progress=dot:mega -i - -O build/bob.jar || travis_terminate 1
  - java -jar build/bob.jar --email foo@bar.com --auth 12345 --texture-compression true --bundle-output build/bundle/js-web --platform js-web --archive resolve build bundle || travis_terminate 1

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build/bundle/js-web/hyper_trails
  on:
    branch: master
